/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.googlecode.json.simple.json.simple)
    api(libs.com.google.code.gson.gson)
    api(libs.com.github.davidmoten.word.wrap)
    api(libs.org.knowm.xchart.xchart)
    api(libs.com.github.hopshackle.ntbea)
    api(libs.io.humble.humble.video.all)
    api(libs.tw.edu.ntu.csie.libsvm)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.spark.spark.core.v2.v13)
    api(libs.org.apache.spark.spark.sql.v2.v13)
    api(libs.org.apache.spark.spark.mllib.v2.v13)
    api(libs.commons.io.commons.io)
    api(libs.tech.tablesaw.tablesaw.core)
    api(libs.tech.tablesaw.tablesaw.html)
    api(libs.tech.tablesaw.tablesaw.json)
    api(libs.tech.tablesaw.tablesaw.jsplot)
    api(libs.tech.tablesaw.tablesaw.excel)
    api(libs.org.testng.testng)
    api(libs.com.globalmentor.hadoop.bare.naked.local.fs)
    testImplementation(libs.junit.junit)
}

group = "ai.tabletopgames"
version = "1.0-SNAPSHOT"
description = "ModernBoardGame"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
    useTestNG()
}
